### ISSUE TITLE
Pattern matching doesn't seem to work as expected

### ISSUE THREAD

**Issue by webbower** [swimmadude66/webpack-nomodule-plugin#9]
Hiya. I found this plugin to help with only loading polyfills for old browsers. However, it was not as straightforward to implement as it seemed. In dev build, my polyfill file was set as an entry and it output as `/path/to/polyfill.chunk.js` which I could see in my HTML output. So I tried `polyfill.**.js` like in your example in the README. Didn't work. I tried various other ways (my familiarity with globbing patterns is not super strong) and nothing seemed to work. I looked at the source and saw that your tests also did the same thing. I found in the source that `minimatch` is used for the pattern matching. So I tried playing with `minimatch` in an isolated environment.

Long story short, after playing with `minimatch` on its own, the solution was that I needed to prefix my pattern with `**/` in order for it to match the whole path. But your README example AND your test code didn't include this. The behavior that works seemed to imply `{ matchBase: true }` for `minimatch` to only perform the comparison against the basename of the asset. So the working pattern that properly applied `nomodule` was `**/polyfill.**.js`. I'm not sure how it's working in your test cases but I wanted to let you know that there may be a bug in your test code and that your README example may mismatch with how the matching works.

Thanks for your time. I'm looking forward to using your bundle now that I figured out how to make it work.

**Comment by localyost3000** [comment]
Hey, thanks for opening this! Without seeing the rest of your webpack.config I can't be certain, but it sounds as though the reason the example pattern is not working for you is that your chunks are not output in the root of the dist file. In the tests, examples, and my projects which use this, I tend to place all the webpack output directly in the dist folder, with no nesting.

The glob pattern you describe (`**/`) matches 0 or more directories, so it makes sense that would be needed to match a file output as `dist/js/polyfill.chunk.js`. I will definitely add some text to the README, though, as I imagine your situation is far from unique.

If I am way off-base and your webpack output is in fact flat, then I will absolutely take a look at what's going on here. Thanks again for bringing this up, and I hope the library helps now that its working for you!

**Comment by webbower** [comment]
Hey. That makes sense why the lack of `**/` prefix works for you and didn't for me. Probably worth adding a note to the README about prefixing with that otherwise other people may assume that it just matches against the file name and not the whole path. Thanks!

**Comment by localyost3000** [comment]
100%. I've added a short blurb in the readme about basics of globs, but please let me know if that's still insufficient.
